michellab/BioSimSpace

python/BioSimSpace/Metadynamics/_metadynamics.py
I don't know if it is just me, but I was experiencing an `import` failure upon doing a
```
import BioSimSpace as BSS
```
which is fixed by this commit.
=> Fixes import failure

python/BioSimSpace/FreeEnergy/_free_energy.py, python/BioSimSpace/Process/_process.py, python/BioSimSpace/Process/_somd.py, test/Gateway/test_node.py
A few changes needed to get the unit tests to pass on Windows.
- The Windows shell does not understand single quotes, only double quotes
- Windows does not support symlinks, so instead of calling the `analyse_freenrg` and `somd` symlinks we need to call `sire_python.exe` and pass the script as first argument
=> Get the unit tests to pass on Windows

test/Process/test_somd.py
If test_somd.py fails due to a `RuntimeError: Particle coordinate is nan` error, it should pass with a warning rather than failing, as it is not really a problem with BSS or SOMD.
=> Avoid that test_somd.py fails due to OpenMM nan issues

python/BioSimSpace/_SireWrappers/_molecule.py, python/BioSimSpace/_SireWrappers/_system.py
Currently running BioSimSpace multiple times on the same input yields completely different outputs (seen on `prmtop` and `inpcrd` files).
This happens because the Sire `MolGroupsBase::molecules()` method returns molecules by iterating on a `QHash`, so they are not ordered as in the input file, but based on a hash.
Using the `MolGroupsBase::molecules(const MGID &mgid)` method ensures that molecules are output in the same order as in the input.
While this does not change the outcome of a calculation in any way or form, having consistent outputs is important for 1) tidiness 2) spotting out differences/mistakes.
Also sections in the `.pert` file are currently output based on a Python `dict` ordering rather than being consistently sorted based on same criterion. Again, this does not change …
=> Ensure consistent output across different runs with same input

doc/source/api/index_Box.rst, python/BioSimSpace/Box/__init__.py, python/BioSimSpace/Box/_box.py, python/BioSimSpace/FreeEnergy/_binding.py, python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Process/_namd.py, python/BioSimSpace/Process/_somd.py, python/BioSimSpace/Solvent/_solvent.py, python/BioSimSpace/__init__.py, test/Process/test_single_point_energy.py
Building from [this](https://github.com/michellab/Sire/pull/325) Sire pull request, I have updated BioSimSpace to provide support for triclinic simulation boxes. A quick summary is as follows:
* Added functionality for generating triclinic solvent boxes using `gmx editconf` and `gmx solvate`.
* New `BioSimSpace.Box` package for generating triclinic box parameters. (These can be used to create solvent boxes, or can be passed to `FreeEnergy.Binding` to create a custom box for the free leg.
* Updated `BioSimSpace.Process.Namd` to generate configuration files for triclinic simulation boxes. (AMBER and GROMACS handle triclinic cells automatically through the coordinate files.)
* Added single-point energy test for AMBER/GROMACS using a triclinic simulation box.
(Note that this pull request can …
=> Triclinic space support

doc/source/changelog.rst, python/BioSimSpace/MD/_md.py, python/BioSimSpace/Process/__init__.py, python/BioSimSpace/Process/_amber.py, python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Process/_namd.py, python/BioSimSpace/Process/_openmm.py, python/BioSimSpace/Process/_process.py, python/BioSimSpace/Trajectory/_trajectory.py, python/BioSimSpace/Types/_temperature.py, python/BioSimSpace/_SireWrappers/_system.py, test/Process/test_openmm.py
This pull request implements `BioSimSpace.Process.OpenMM`, allowing the BioSimSpace to generate scripts using the OpenMM Python API that support a range of molecular simulation protocols. Executing a process runs the script using the `sire_python` interpreter, which can then be monitored from the BioSimSpace Process, e.g. getting state information from log files, trajectory frames, etc.
Currently the only point of confusion is the way in which OpenMM implements molecular minimisations, which varies depending on the chosen integrator. The examples described [here](http://docs.openmm.org/latest/userguide/application.html) use a Langevin integrator at 300 K, for which the stochastic component still seems active during the minimisation. For consistency with minimisers from other MD engines, …
=> Added support for running molecular simulations using OpenMM

doc/source/nodes.rst, python/BioSimSpace/Gateway/_node.py, python/BioSimSpace/Gateway/_requirements.py
This pull request adds functionality to export [Common Workflow Language](https://www.commonwl.org/) (CWL) wrappers from a BioSimSpace node, for example:
```python
python minimisation.py --export-cwl
```
This writes a wrapper called `minimisation.cwl` in the current directory, which can be run as part of CWL workflow as follows:
```bash
cwltool minimisation.cwl config.yaml
```
Depending on your setup, you might need to run:
```bash
cwltool --preserve-entire-environment minimisation.cwl config.yaml
```
Here `config.yaml` is a CWL YAML configuration file, e.g.:
```yaml
files:
- {class: File, path: /home/lester/BioSimSpace/demo/amber/ala/ala.top}
- {class: File, path: /home/lester/BioSimSpace/demo/amber/ala/ala.crd}
steps:
1000
```
At present, using BioSimSpace within CWL is limited to the …
=> Add support for exporting CWL wrappers from BioSimSpace nodes

python/BioSimSpace/Parameters/Protocol/_amber.py, python/BioSimSpace/Parameters/Protocol/_openforcefield.py, python/BioSimSpace/Parameters/Protocol/_protocol.py, python/BioSimSpace/Parameters/_process.py, python/BioSimSpace/_Exceptions/_exceptions.py
Following yesterday's discussions, I have implemented @j-wags and @mattwthompson's recommendation to create an OpenFF Molecule using an intermediate SDF file written by RDKit, since this quietly handles some tricky sanitisation issues.
I've also added some fixes to correctly expand verbose error messages when the parameterisation process is run as a background thread.
=> OpenFF integration improvements

python/BioSimSpace/Align/_align.py, python/BioSimSpace/Align/_lomap/lomap_networkgen.py, python/setup.py
Adjusted `_Align.py` such that it can now take in a variable `scores_file` (will throw an exception when `names` is not given simultaneously). This file contains user-input edge scorings that LOMAP can use instead of the native LOMAP score. `_Align.py` contains some checks to see if all possible combinations of `names` are in `scores_file`; the ordering should not matter for LOMAP because `lomap_networkgen.py` parses the file per perturbation.
I built the `--ml_pd` parameter and subsequent `ml_pd` path string passing in a similar way to how the fingerprint (`-f`) is passed to `compute_mtx()`.
Bonus: adjusted `generateNetwork()` such that now it uses a .mol2 intermediate instead of .pdb by naming molecules as {index}_{name}.mol2. With some small changes in the rdkit preparation, now pydot …
=> Feature feed lomap scores

python/BioSimSpace/FreeEnergy/_free_energy.py, python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Process/_somd.py, python/BioSimSpace/Protocol/_free_energy.py, python/BioSimSpace/_SireWrappers/_molecule.py
This PR relates to #165.
This is a first implementation of the multi-step protocol; with this it is now possible for the user to define a `pert_type` in `BSS.Protocol.FreeEnergy()`. If not defined, the setup will default to a normal FEP setup (i.e. 1 step). I've built it into Protocol because it gives users the freedom to define specific numbers of lambda windows per step.
There are several caveats to the current implementation:
- when building multiple steps, `BSS.Protocol.FreeEnergy()` will have to be called multiple times. For instance:
```
protocol = BSS.Protocol.FreeEnergy(num_lam=10, pert_type="1_discharge_soft")
BSS.FreeEnergy.Solvation(system_solvated, protocol, work_dir="output/1_discharge_soft")
protocol = BSS.Protocol.FreeEnergy(num_lam=15, pert_type="2_vanish_soft") …
```
=> Feature multi step perturbation 3

doc/source/api/index_Box.rst, doc/source/api/index_Stream.rst, python/BioSimSpace/Stream/__init__.py, python/BioSimSpace/Stream/_stream.py, python/BioSimSpace/_Exceptions/_exceptions.py, python/BioSimSpace/_SireWrappers/_sire_wrapper.py, python/BioSimSpace/__init__.py, test/Stream/test_stream.py
This pull request adds long overdue support for streaming wrapped Sire objects, i.e. the objects from [BioSimSpace._SireWrappers](https://biosimspace.org/api/index_SireWrappers.html). This facilitates the streaming of systems containing perturbable molecules and _should_ make it easier to pass information between BioSimSpace nodes. This also opens the possibility of stream support for complex objects that contain a mixture of pure Python attributes and wrapped Sire objects, i.e. the Python attributes could be pickled separately as a dictionary or dataclass, while the wrapped Sire object is streamed. These could be streamed back from file independently, then recombined.
=> Addded support for streaming wrapped Sire objects

python/BioSimSpace/Align/_align.py
some more tweaks to `generateNetwork()` that were necessary for my work. 
1) `molecules` can now also be passed as a list of RDKit molecules instead of BSS molecules. In this case, the intermediate ligand files written to `work_dir` are SDF. The reason for this is that for ~60% of test cases (FEP congeneric series), RDKit kekulization fails when using MOL2 inputs, i.e. making LOMAP fail. See some other discussions: https://github.com/MobleyLab/Lomap/issues/26 and https://sourceforge.net/p/rdkit/mailman/message/35999854/
Using an SDF intermediate makes all molecules pass; presumably this is what Cresset is doing as well (see Max's comment in the linked LOMAP issue).
2) I'm generating a large number of networks for many different series and I want to compare networks after letting my code …
=> Lomap improvements again

python/BioSimSpace/Align/_align.py, python/BioSimSpace/Align/_lomap/dbmol.py
this PR adds functionality to `BSS.Align._align.generateNetwork()` such that it now ingests a user-specified integer (`n_edges_forced`) that forces the number of edges included in the perturbation network. This is useful for general practice as typically FEP campaigns have a pre-set amount of compute available. It also allows direct comparison between networks generated with different types of inputs (i.e. beside LOMAP-Score using the `links_file`).
I have included validation (checks that `n_edges_forced` is an _int_ and checks that it is higher than 0 and at most a fully-connected network.
There are three situations as described in the code:
1. the user-specified number of edges is already suggested by LOMAP, in this case do nothing.
2. the user-specified number of edges is higher than …
=> Feature lomap force n edges

python/BioSimSpace/FreeEnergy/_relative.py
Concerning a transformation in SOMD (ejm31 to ejm42 tyk2 - https://github.com/michellab/BioSimSpace/pull/244#issuecomment-985444208 ) the analysis resulted in a large error because subsampling resulted in less than 50 samples for the bound leg.
When this transformation was rerun, the free energy analysis subsampling still resulted in less than 50 samples for the bound leg and even more vastly wrong results. With the subsampling turned off then for that leg, the results are much better (the experimental is -0.24 kcal/mol)
  | result (kcal/mol) | error
-- | -- | --
subsampling on and resulting in less than 50 samples | -14.7274 | 1.2025
subsampling off if less than 50 samples for that leg | -0.201 | 0.0727
So I think this code change may be a way to avoid that automatically without manually …
=> SOMD analysis without subsampling

python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_molecule.py, python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_residue.py, python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_system.py, test/Sandpit/Exscientia/_SireWrappers/test_sire_wrappers.py
This PR adds `__contains__` operators to the wrapped Sire objects within the Exscientia sandpit. This allows the user to check whether objects contain other object, e.g.:
```python
molecule in system
residue in system
atom in system
residue in molecule
atom in molecule
atom in residue
```
=> Copy __contains__ functionality into Exscientia sandpit.

python/BioSimSpace/Sandpit/Exscientia/Types/_general_unit.py, python/BioSimSpace/Types/_general_unit.py, test/Sandpit/Exscientia/Types/test_general_unit.py, test/Types/test_general_unit.py
This PR fixes the value when dimensionless `GeneralUnit` objects are converted to float. See #332.
=> Fix value during dimensionless GeneralUnit conversion. [closes #332]

python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py, test/Process/test_gromacs.py, test/Sandpit/Exscientia/Process/test_gromacs.py
This PR addresses issue #338 and ensures that the water topology is swapped to GROMACS format prior to writing the custom Gro87 file needed for vacuum simulations, i.e. where an infinite periodic box is added.
=> Swap water topology before writing custom GRO file for vacuum simulations

python/BioSimSpace/Align/_align.py, python/BioSimSpace/Sandpit/Exscientia/Align/_align.py
This PR resolves #348 by adding support for our new SDF parser within `BioSimSpace.Align.generateNetwork`. SDF is generally more reliable with LOMAP than Mol2, so should be used whenever the passed molecules have SDF in their `fileformat` property. The PR also checks the return type of any RDKit IO operation, since it may return `None` rather than raising an exception on failure.
=> Add support for SDF parser and check for NoneType from RDKit.

python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py, python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_molecule.py, python/BioSimSpace/Sandpit/Exscientia/_SireWrappers/_system.py, python/BioSimSpace/_SireWrappers/_molecule.py, python/BioSimSpace/_SireWrappers/_system.py, test/Sandpit/Exscientia/_SireWrappers/test_molecule.py, test/_SireWrappers/test_molecule.py
This PR adds an additional option, `use_coordinates`, that allows the user to specify whether to use the current molecular coordinates to compute the connectivity during hydrogen mass repartitioning. If `False`, the `connectivity` property will be used, i.e. the bonding from the topology generated by the force field.
The PR also updates the unit tests to ensure that the repartitioning is invertible.
Edits are backwards compatible, but will need the latest Sire (currently building) to ensure that the `connectivity` is used by default.
Cheers.
=> Allow user to specify whether to use connectivity or coordinates during HMR.

python/BioSimSpace/Process/_gromacs.py
Hi, This PR adds a new parameter `prev_cpt` for Gromacs Process to continue the simulation from the previous run. 
Context: 
---
I've followed the equilibration protocol (`all restrained short NVT -> backbone restrained NVT -> NVT -> heavy atom restrained  NPT -> NPT`) in [BioSimSpace Tutorial](https://github.com/michellab/BioSimSpaceTutorials/blob/main/04_fep/execution_model/scripts/BSSligprep.py) for a while, using Gromacs as MD engine, instead of  PMEMD.  But my simulation always suffered from `#WARNING SUBSAMPLING ENERGIES RESULTED IN LESS THAN 50 SAMPLES` when analyzing the result. 
As Julien suggested [here](https://github.com/michellab/Sire/issues/90#issuecomment-165442941), it means that the simulation does not start from a well-equilibrated trajectory (I've checked the overlap …
=> Add a parameter for Gromacs Process to continue simulation from the previous run. 

python/BioSimSpace/Process/_gromacs.py, python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py, python/BioSimSpace/Sandpit/Exscientia/Trajectory/_trajectory.py, python/BioSimSpace/Trajectory/_trajectory.py, test/Sandpit/Exscientia/Trajectory/test_trajectory.py, test/Trajectory/test_trajectory.py
This PR fixes some issues with the recent trajectory updates caused by caching in Sire.IO. This led caused trajectory frames with the same filename to not be re-read, even when the contents of the file was different, or when the file was deleted and re-written (with the same name). We now use unique file names for all frames extracted by MDTraj/MDAnalysis, which avoids the problem. (For some reason, the problem only became apparent when going via PDB format frame files.)
=> Fix Sire.IO caching issues with trajectory frames.

docker/conda/recipe/template.yaml, python/setup.py
Hello,
Recent changes to ipywidgets have [broken NGLView](https://github.com/nglviewer/nglview/issues/1032) - ensuring version <8 avoids any issues.
Thanks,
Finlay
=> Set ipywidgets<8 to Avoid Issues with NGLView
